import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createGame,STATIONS,SETTINGS,spawnTask,tick,movePlayer,startTask,cancelTask,finishTask,failAttempt,pauseGame,resumeGame} from '../src/simulation.ts';

function enter(s,task=s.tasks[0]){const st=STATIONS.find(v=>v.id===task.station);s.player.x=st.x;s.player.z=st.z;assert.equal(startTask(s),true);return task;}
function advance(s,seconds){for(let i=0;i<seconds*60;i++)tick(s,1/60);}
test('a fresh game has two distinct tasks and bounded initial state',()=>{for(const difficulty of Object.keys(SETTINGS)){const s=createGame(difficulty,99);assert.equal(s.tasks.length,2);assert.equal(new Set(s.tasks.map(t=>t.station)).size,2);assert.equal(s.time,SETTINGS[difficulty].duration);assert.equal(s.phase,'playing');}});
test('seeded scheduling is deterministic, unique, capped and includes all stations',()=>{for(let seed=1;seed<=30;seed++){const a=createGame('normal',seed),b=createGame('normal',seed),seen=new Set();for(let i=0;i<9;i++){const t=a.tasks[0];seen.add(t.station);enter(a);enter(b);finishTask(a,1);finishTask(b,1);assert.deepEqual(a,b);assert.ok(a.tasks.length<=4);assert.equal(new Set(a.tasks.map(t=>t.station)).size,a.tasks.length);}assert.equal(seen.size,6,`all stations, seed ${seed}`);}});
test('task range is enforced; cancel leaves original deadline intact',()=>{const s=createGame();assert.equal(startTask(s),false);const t=enter(s);const original=t.remaining;advance(s,3);assert.equal(t.remaining,original);cancelTask(s);advance(s,2);assert.ok(t.remaining<original-1.9);assert.equal(s.activeTask,null);});
test('completion scores once, clamps quality, and rejects invalid input',()=>{const s=createGame();enter(s);for(const q of [NaN,Infinity,-1,0])assert.equal(finishTask(s,q),false);assert.equal(s.completed,0);assert.equal(s.score,0);assert.equal(finishTask(s,2),true);const score=s.score;assert.ok(score>0&&Number.isFinite(score));assert.equal(finishTask(s,1),false);assert.equal(s.score,score);});
test('pause freezes timers, movement, deadlines, spawning and restores minigame',()=>{const s=createGame();enter(s);pauseGame(s);const snapshot=structuredClone(s);advance(s,30);movePlayer(s,1,1,.1,true);failAttempt(s);assert.deepEqual(s,snapshot);resumeGame(s);assert.equal(s.phase,'minigame');assert.notEqual(s.activeTask,null);});
test('expired tasks penalize exactly once',()=>{const s=createGame();s.tasks[0].remaining=.005;tick(s,1/60);assert.equal(s.mistakes,1);const chaos=s.chaos;tick(s,1/60);assert.equal(s.mistakes,1);assert.ok(s.chaos-chaos<1);});
test('zero clock and maximum chaos terminate irreversibly',()=>{for(const reason of ['time','chaos']){const s=createGame();if(reason==='time')s.time=.001;else s.chaos=99.9999;tick(s,.1);assert.equal(s.phase,'lost');const copy=structuredClone(s);advance(s,60);movePlayer(s,1,1,.1,true);finishTask(s,1);assert.deepEqual(s,copy);}});
test('all three campaigns reach finale and win without overcounting',()=>{for(const difficulty of Object.keys(SETTINGS)){const s=createGame(difficulty,17);for(let i=0;i<s.target;i++){enter(s);advance(s,2);finishTask(s,1);}assert.equal(s.completed,s.target);assert.equal(s.phase,'playing');assert.equal(s.finalJob,true);assert.equal(s.tasks.length,1);assert.equal(s.tasks[0].station,'mainframe');enter(s);finishTask(s,1);assert.equal(s.phase,'won');assert.equal(s.finalDone,true);assert.equal(s.completed,s.target);assert.equal(s.activeTask,null);const copy=structuredClone(s);advance(s,50);assert.deepEqual(s,copy);}});
test('movement respects bounds, collision and diagonal speed normalization',()=>{const a=createGame(),b=createGame();a.player.x=b.player.x=0;a.player.z=b.player.z=0;movePlayer(a,1,0,1/60);movePlayer(b,1,1,1/60);assert.ok(Math.abs(Math.hypot(a.player.x,a.player.z)-Math.hypot(b.player.x,b.player.z))<1e-8);const s=createGame();s.player.x=-6;s.player.z=-3.4;for(let i=0;i<120;i++)movePlayer(s,0,-1,1/60,true);assert.ok(s.player.z>=-3.95);for(let i=0;i<2000;i++)movePlayer(a,1,0,1/60);assert.ok(a.player.x<=8.75);});
test('dash has a cooldown and is blocked during minigames',()=>{const s=createGame();movePlayer(s,1,0,1/60,true);assert.equal(s.player.dashCooldown,2.7);tick(s,.1);movePlayer(s,1,0,1/60,true);assert.ok(s.player.dashCooldown<2.7);enter(s);const p=structuredClone(s.player);movePlayer(s,1,1,.1,true);assert.deepEqual(s.player,p);});
test('active-task mistakes break combo and can trigger loss',()=>{const s=createGame();enter(s);s.combo=5;s.chaos=98;failAttempt(s);assert.equal(s.mistakes,1);assert.equal(s.combo,0);assert.equal(s.chaos,100);assert.equal(s.phase,'lost');assert.equal(s.activeTask,null);});
test('deadlines and scores remain finite in extended idle runs',()=>{for(let seed=0;seed<20;seed++){const s=createGame('normal',seed);advance(s,1000);assert.equal(s.phase,'lost');assert.ok(s.time>=0&&s.chaos<=100&&s.chaos>=0);assert.ok(Number.isFinite(s.score));assert.ok(s.tasks.length<=4);}});
